#|
 This file is a part of cl-visa32 project.
|#

(in-package :cl-user)
(defpackage cl-visa32
  (:nicknames :visa32)
  (:use :cl)
  (:import-from :cl-visa32.operations
                :vi-assert-intr-signal
                :vi-assert-trigger
                :vi-assert-util-signal
                :vi-buf-read
                :vi-buf-write
                :vi-clear
                :vi-close
                :vi-disable-event
                :vi-discard-events
                :vi-enable-event
                :vi-event-handler
                :vi-find-next
                :vi-find-rsrc
                :vi-flush
                :vi-get-attribute
                :vi-gpib-command
                :vi-gpib-control-atn
                :vi-gpib-control-ren
                :vi-gpib-pass-control
                :vi-gpib-send-ifc
                :vi-in8
                :vi-in16
                :vi-in32
                :vi-install-handler
                :vi-lock
                :vi-map-address
                :vi-map-trigger
                :vi-mem-alloc
                :vi-mem-free
                :vi-move
                :vi-move-async
                :vi-move-in8
                :vi-move-in16
                :vi-move-in32
                :vi-move-out8
                :vi-move-out16
                :vi-move-out32
                :vi-open
                :vi-open-default-rm
                :vi-out8
                :vi-out16
                :vi-out32
                :vi-parse-rsrc
                :vi-parse-rsrc-ex
                :vi-peek8
                :vi-peek16
                :vi-peek32
                :vi-poke8
                :vi-poke16
                :vi-poke32
                :vi-printf
                :vi-queryf
                :vi-read
                :vi-read-async
                :vi-read-stb
                :vi-read-to-file
                :vi-scanf
                :vi-set-attribute
                :vi-set-buf
                :vi-sprintf
                :vi-sscanf
                :vi-status-desc
                :vi-terminate
                :vi-uninstall-handler
                :vi-unlock
                :vi-unmap-address
                :vi-unmap-trigger
                :vi-usb-control-in
                :vi-usb-control-out
                :vi-vprintf
                :vi-vqueryf
                :vi-vsscanf
                :vi-vxi-command-query
                :vi-wait-on-event
                :vi-write
                :vi-write-async
                :vi-write-from-file)
  (:export :vi-assert-intr-signal
           :vi-assert-trigger
           :vi-assert-util-signal
           :vi-buf-read
           :vi-buf-write
           :vi-clear
           :vi-close
           :vi-disable-event
           :vi-discard-events
           :vi-enable-event
           :vi-event-handler
           :vi-find-next
           :vi-find-rsrc
           :vi-flush
           :vi-get-attribute
           :vi-gpib-command
           :vi-gpib-control-atn
           :vi-gpib-control-ren
           :vi-gpib-pass-control
           :vi-gpib-send-ifc
           :vi-in8
           :vi-in16
           :vi-in32
           :vi-install-handler
           :vi-lock
           :vi-map-address
           :vi-map-trigger
           :vi-mem-alloc
           :vi-mem-free
           :vi-move
           :vi-move-async
           :vi-move-in8
           :vi-move-in16
           :vi-move-in32
           :vi-move-out8
           :vi-move-out16
           :vi-move-out32
           :vi-open
           :vi-open-default-rm
           :vi-out8
           :vi-out16
           :vi-out32
           :vi-parse-rsrc
           :vi-parse-rsrc-ex
           :vi-peek8
           :vi-peek16
           :vi-peek32
           :vi-poke8
           :vi-poke16
           :vi-poke32
           :vi-printf
           :vi-queryf
           :vi-read
           :vi-read-async
           :vi-read-stb
           :vi-read-to-file
           :vi-scanf
           :vi-set-attribute
           :vi-set-buf
           :vi-sprintf
           :vi-sscanf
           :vi-status-desc
           :vi-terminate
           :vi-uninstall-handler
           :vi-unlock
           :vi-unmap-address
           :vi-unmap-trigger
           :vi-usb-control-in
           :vi-usb-control-out
           :vi-vprintf
           :vi-vqueryf
           :vi-vsscanf
           :vi-vxi-command-query
           :vi-wait-on-event
           :vi-write
           :vi-write-async
           :vi-write-from-file))

(in-package cl-visa32)
 
;; blah blah blah.
